### PR TITLE
CheckAccessKeys in Cloudformation yaml

### PR DESCRIPTION
**Pull request by pmbohm**

### CODE REVIEW

**Comment by akashisama** [comment]
I added a commit on Friday that makes this work. Two things I'm unsure about though:

### Lambda Code Deployment
We need to work out how we're going to update the function's code. We have a custom function to deal with this in aws-wps, but I think that's overkill for these small tasks. I was looking at the Serverless Application Framework mixed with the ```aws cloudformation package``` command and it looks quite convenient. 
http://docs.aws.amazon.com/lambda/latest/dg/with-api-example-use-app-spec.html. 
http://docs.aws.amazon.com/lambda/latest/dg/serverless-deploy-wt.html#serverless-deploy
Within our YAML file we would specify the location of the code relative to the YAML on our _local machines_. We would then run the package command, passing in the YAML and a bucket name. The package command zips up the code, uploads it to the bucket with a randomized name, and creates a new YAML which replaces the reference to the local machine code and points instead to S3. We would then run deploy on the generated YAML and voilà the new code is deployed.

### SNS Topic
This template creates a new custom notification service. Wouldn't it would be better to provide it with a pre-existing SNS topic? If we do it this way then there's a manual step needed to verify the email address when we run up a new stack.

**Comment by lwgordonimos** [comment]
> Wouldn't it would be better to provide it with a pre-existing SNS topic?

@akashisama possibly, but only if it is one that has been advertised using the "Exports" mechanism of Cloudformation, implying that another central infrastructure stack is providing it. We shouldn't roll out new stacks which make any assumptions about the infrastructure outside of the stack except via an Export. This is to ensure that all resources are managed by something.

It's better to have a resource being largely duplicated in a template, and be duplicated in a stack (and be managed), than to have implied dependencies which aren't *formally* defined anywhere properly (i.e. manually created or fixed name from another stack).

Re: email address validation: there shouldn't be a need for this type of stack to constantly validate new email addresses? What address that we don't current have verified would this ever need to use?

**Comment by akashisama** [comment]
> Re: email address validation: there shouldn't be a need for this type of stack to constantly validate new email addresses? What address that we don't current have verified would this ever need to use?
@lwgordonimos the problem is the email doesn't start off verified. If you look at the SNS of this stack in dev account, the email sys.admin@emii.org.au hasn't been verified and therefore emails aren't being sent.

**Comment by akashisama** [comment]
This should be ready to review/merge now

**Pull request merged**
