### PR TITLE
Add test config for aus_chla_db

### PR DESCRIPTION
**Pull request by jonescc**
Needs testing

### CODE REVIEW

**Comment by jonescc** [comment]
Tested, but fails on 6-nec-hob (and prod) due to an ssl protocol issue (recently fixed for other harvesters).  Runs on 9-nec-hob as this issue is fixed with java 8 but can't compare results.   Results should be confirmed to be correct before promoting.

**Comment by gsatimos** [comment]
@lbesnard we can't run this on `6-nec-hob` because of the SSL issue (mentioned by @jonescc above).
Are you able to take a look at the result set for `9-nec-hob` that I've just pushed a commit for and say if it's looks okay?

**Comment by lbesnard** [comment]
@gsatimos I don't know anything about this harvester/collection, so honestly, my judgement on the matter would be more than amateurish. But yes, it looks like it's working

**Comment by gsatimos** [comment]
sorry @lbesnard. I thought this harvester was one of yours. all good

**Comment by lbesnard** [comment]
@gsatimos , no worries at all. The only issue is that it was xavier's, and I don't think anyone in the team knows about this one. The output looks good to me, but that's all I can say really.

**Comment by gsatimos** [comment]
@jonescc do we need an issue raised for this one?

**Comment by gsatimos** [comment]
@ggalibert the `aus_chla_db` harvester is not working in `6-nec-hob` because of an SSL issue. We're thinking that we should omit this one from further testing on RC and PROD. Is that okay with you?

**Comment by gsatimos** [comment]
after discussing with @atkinsn @ggalibert and @smancini we're going to:
1. keep this test (i.e. I'll merge it since it could be useful later)
2. the `aus_chla_db` harvester will remain in the `harvesters` repo
3.  `aus_chla_db` will be removed from rc and prod pipelines as part of the upcoming roll-out of talend 7 harvesters for testing.

**Pull request merged**
