### PR TITLE
Add outputs for vpc and subnets to lambda_subnet cloudformation templ…

### PR DESCRIPTION
**Pull request by akashisama**
…ate. Use the outputs in geowebcache_seeder cloudformation template.

### CODE REVIEW

**Comment by lwgordonimos** [comment]
Looks pretty reasonable in general, but how can we test it?

**Comment by akashisama** [comment]
I've run up a lambda_subnet stack and a geowebcache_seeder stack in the dev account and the correct subnets have been passed to the lambda function.

**Comment by akashisama** [comment]
This should be ready to merge now

**Comment by akashisama** [comment]
There was one strange annoyance that we'll have to keep in mind in the future. When I tried to update the stack I got the error "The provided execution role does not have permissions to call CreateNetworkInterface on EC2" which is the error you'd expect if you hadn't given the lambda function the right permissions in the IAM role, but we had. The dependency order was correct as well: the IAM role was altered before the function. But none the less, I had to update the stack in a 2 step process, 1st update the IAM role, then update the rest.

**Pull request merged**
