### PR TITLE
Add test config for auv

### PR DESCRIPTION
**Pull request by jonescc**
Needs testing

### CODE REVIEW

**Comment by jonescc** [comment]
Added required manifests to kick off processing.  Tested OK on 6-nec-hob.

Results:  
[auv.zip](https://github.com/aodn/utilities/files/3205747/auv.zip)

Looks to me like the delete processing isn't clearing out the map data correctly!

**Comment by jonescc** [comment]
Looks like there's a difference in output between tos 5 and tos 7 for auv_trajectory_map in step 1 and after

```
--- /home/craigj/git-repos/aodn/utilities/pipeline/talend_test/harvest_results/6-nec-hob.emii.org.au/auv/action_0_ADD /auv/auv_trajectory_map.csv
+++ /home/craigj/git-repos/aodn/utilities/pipeline/talend_test/harvest_results/9-nec-hob.emii.org.au/auv/action_0_ADD /auv/auv_trajectory_map.csv
@@ -1,3 +1,3 @@
 file_id,url,size,campaign_name,dive_name,time_coverage_start,time_coverage_end,PSAL_b,TEMP_b,geom
-1,IMOS/AUV/Tasmania201808/r20180823_215013_SS08_Beagle_Shelf_13/hydro_netcdf/IMOS_AUV_B_20180823T215019Z_SIRIUS_FV00.nc,289896,Tasmania201808,r20180823_215013_SS08_Beagle_Shelf_13,2018-08-24 07:50:20,2018-08-24 09:23:42,t,t,0102000020E6100000020000002B725BAC5B63624014B4463615AD43C0E22FFF089F63624040B38B9A69AC43C0
-2,IMOS/AUV/Tasmania201808/r20180823_215013_SS08_Beagle_Shelf_13/hydro_netcdf/IMOS_AUV_ST_20180823T215019Z_SIRIUS_FV00.nc,266216,Tasmania201808,r20180823_215013_SS08_Beagle_Shelf_13,2018-08-24 07:50:20,2018-08-24 09:23:42,t,t,0102000020E6100000020000002B725BAC5B63624014B4463615AD43C0E22FFF089F63624040B38B9A69AC43C0
+1,IMOS/AUV/Tasmania201808/r20180823_215013_SS08_Beagle_Shelf_13/hydro_netcdf/IMOS_AUV_B_20180823T215019Z_SIRIUS_FV00.nc,289896,Tasmania201808,r20180823_215013_SS08_Beagle_Shelf_13,2018-08-23 21:50:20,2018-08-23 23:23:42,t,t,0102000020E6100000020000002B725BAC5B63624014B4463615AD43C0E22FFF089F63624040B38B9A69AC43C0
+2,IMOS/AUV/Tasmania201808/r20180823_215013_SS08_Beagle_Shelf_13/hydro_netcdf/IMOS_AUV_ST_20180823T215019Z_SIRIUS_FV00.nc,266216,Tasmania201808,r20180823_215013_SS08_Beagle_Shelf_13,2018-08-23 21:50:20,2018-08-23 23:23:42,t,t,0102000020E6100000020000002B725BAC5B63624014B4463615AD43C0E22FFF089F63624040B38B9A69AC43C0
```

**Comment by jonescc** [comment]
Looks like the harvester is time zone sensitive.  When preparing the wms data, the TIME data goes from timestamp with time zone (measurements_b/st) to timestamp with time zone (measurements_merged_data) to timestamp without time zone (table_master) and then to timestamp without time zone (visualiation_wms.   I think this is problematic as the meaning of timestamp without time zone depends on the server time and this data is streaming through java on another server also potentially with different time zone settings.   This is the reason why we should always store timestamps in timestamp with time zones.  We use views to specifically convert this to UTC time to workaround geoserver time zone issues only.

**Comment by jonescc** [comment]
This test_config is ready for review.

**Comment by lbesnard** [comment]
> Looks like the harvester is time zone sensitive. When preparing the wms data, the TIME data goes from timestamp with time zone (measurements_b/st) to timestamp with time zone (measurements_merged_data) to timestamp without time zone (table_master) and then to timestamp without time zone (visualiation_wms. I think this is problematic as the meaning of timestamp without time zone depends on the server time and this data is streaming through java on another server also potentially with different time zone settings. This is the reason why we should always store timestamps in timestamp with time zones columns. We use views to specifically convert this to UTC time to workaround geoserver time zone issues only.

@jonescc so we agree that table_master should be 
timestamp **with** time zone (table_master)

**Comment by gsatimos** [comment]
merging this. this has been noted on the spreadsheet as needing timezone issue fix

**Pull request merged**
