### PR TITLE
Add test config for aatams_acoustic_qc

### PR DESCRIPTION
**Pull request by jonescc**
Time zone processing issue with this harvester as well.

### CODE REVIEW

**Comment by jonescc** [comment]
6-nec-hob test results: [aatams_acoustic_qc.zip](https://github.com/aodn/utilities/files/3214828/aatams_acoustic_qc.zip)

**Comment by gsatimos** [comment]
@jonescc 
Noted, that there is time time zone issue, but the `atf_acoustic_qc_detections_map` table has a `colour` column that needs to be excluded.

**Comment by jonescc** [comment]
Hmm.. Looks like I'd already made the change but hadn't pushed it up.  It's been pushed up now

**Comment by lbesnard** [comment]
@gsatimos not sure that we wanted to merge this one as yet until this PR https://github.com/aodn/harvesters/issues/744 could be tested?

**Comment by gsatimos** [comment]
@lbesnard we've marked it on our spreadsheet that we're keeping to track issues. We'll definitely be giving it a test once that issue is fixed and merged.

**Pull request merged**
