### PR TITLE
Add test config for aodn_wave_dm

### PR DESCRIPTION
**Pull request by jonescc**
Needs testing

### CODE REVIEW

**Comment by jonescc** [comment]
tested OK on 6-nec-hob

**Comment by gsatimos** [comment]
@jonescc looks like another time zone issue with this one. Can you please run yourself and confirm?

**Comment by jonescc** [comment]
Rerun locally and I can't see any difference.

**Comment by jonescc** [comment]
Actually, I was looking at the wrong directory - yes there is a time difference for aodn_wave_dm_timeseries_map

**Pull request merged**
