### PR TITLE
gn tool

### PR DESCRIPTION
**Pull request by danfruehauf**
Give it a shot guys. It should work nicely.

*Developed on FreeBSD*

### CODE REVIEW

**Comment by lbesnard** [comment]
Are you going to improve this or not ? Really useful tool @danfruehauf  ! should merge it to master. Only thing to take into account is the export back to geonetwork which modifies the owner of records. This didn't suit Nat. Could something be done on this end ?

**Comment by danfruehauf** [comment]
I don't want to say it's a prototype, but obviously those things must be improved. I think @pblain should allocate time for that down the track.

But thanks for the feedback!

**Comment by jkburges** [comment]
This should be merged if it works?

**Comment by danfruehauf** [comment]
It does work. I don't see a reason why it shouldn't be merged :)

**Comment by anguss00** [comment]
Merginate... merginate

**Pull request merged**
