### PR TITLE
Add test config for aodn_mhl_sst

### PR DESCRIPTION
**Pull request by craigrose**

### CODE REVIEW

**Comment by gsatimos** [comment]
there's an issue with this running on `9-nec-hob`. Not much logging to go on at the moment:
```
gsattler@9-nec-hob:~$ cat /mnt/ebs/log/data-services/process.log 
May 28 15:27:45 9-nec-hob ANMN_MHLWAVE: /usr/local/bin/watch-exec-wrapper.sh: line 60: /mnt/ebs/data-services/AODN/MHL/incoming_handler.sh: No such file or directory
May 28 15:27:45 9-nec-hob ANMN_MHLWAVE: Could not process file 'File not handled':
May 28 15:27:45 9-nec-hob ANMN_MHLWAVE: Moving 'File not handled' -> '/mnt/ebs/error/ANMN_MHLWAVE/.20190528-152745'
May 28 15:27:45 9-nec-hob ANMN_MHLWAVE: Could not move 'File not handled' -> '/mnt/ebs/error/ANMN_MHLWAVE/.20190528-152745'
```

@craigrose this is one from last week sorry, but any chance you might know what the issue could be? I'll keep investigating though

**Comment by gsatimos** [comment]
status: waiting for `9-nec-hob` to cook (talend7-testing branch) then will retry this test config

**Comment by gsatimos** [comment]
@craigrose any reason for `aodn_mhl_sst_data` to be commented-out in the test config?
I can confirm that the results are fine on that table across both nodes so perhaps it can be re-instated?

**Comment by bpasquer** [comment]
@gsatimos 
> @craigrose this is one from last week sorry, but any chance you might know what the issue could be? I'll keep investigating though
This is a pipeline 1 shell script error. It is not impacting the processing of the file. You can ignore.  The processing of those files will  be soon moved to Pipeline v2

**Comment by gsatimos** [comment]
thanks @bpasquer . Makes sense to me know. I got the changes you made in data-services deployed at it starting working.

**Pull request merged**
