### PR TITLE
abos_da test config

### PR DESCRIPTION
**Pull request by gsatimos**
@mhidas I've put together this configuration file to test the abos_da pipeline which runs these harvesters:
- abos_currents
- moorings_metadata
- abos_ts

There's a couple things that I need to check with you (so I'm marking this as a draft PR). 

1. for the input file, I've had a look at some logs for this pipeline on `4-nec-hob` and it looks like if I feed through a zip file (was the name of a file `EAC2000-2016.FV01.noADCP.zip` that I found in a log) then it should execute all the harvesters.

I'm not sure though how to create this zip file. Perhaps I can grab all the files from here `s3://imos-test-data/IMOS/ABOS/DA/EAC2000` and zip them up?

2. Do the tables listed make sense for checking the database output.

(@jonescc just tagging you as well)

### CODE REVIEW

**Comment by mhidas** [comment]
I'll make you a  test file.

**Comment by gsatimos** [comment]
works perfectly when run against `6-nec-hob` and `9-nec-hob`. Resulting data is equal. 
@mhidas is an update/delete appropriate for this one?

**Comment by gsatimos** [comment]
hi @mhidas I'm just getting back to working on this test configuration, 
regarding my question above (which I had also forgotten about).., is updating/deleting appropriate for this one?

**Comment by mhidas** [comment]
> is updating/deleting appropriate for this one?

Sorry, I missed that. Yes, it is!

**Comment by mhidas** [comment]
Note that for the update test you only need to edit two of the netCDF files, e.g.:
* Take IMOS_ABOS-DA_TZ_20161101T000000Z_EAC2000_FV01_EAC2000-2018-SBE39TP-100_END-20180504T020329Z_C-20181112T040924Z.nc for abos_ts, as it is the only one that harvests _data_; and
* IMOS_ABOS-DA_ETVZ_20161101T000000Z_EAC2000_FV01_EAC2000-2018-AQUADOPP-CURRENT-METER-1500_END-20180503T015855Z_C-20190218 for abos_currents, but no need to edit any data in it, just change e.g. the deployment_code or instrument_serial_number global attributes.

**Comment by gsatimos** [comment]
thanks @mhidas the above instructions were good.

@jonescc can you please review/merge?

**Pull request merged**
